### ISSUE TITLE
signaltower staging env

### ISSUE THREAD

**Issue by janlelis** [juwi/palava-ansible#2]

**Comment by juwi** [comment]
Ich habe hier mal angefangen aber ich verstehe nicht ganz wie das mit Elixir und der systemd unit ist. Läuft die "Erkennung" dessen was da gestartet wird über das WorkingDirectory?

**Comment by farao** [comment]
Hm, was genau meinst du mit Erkennung? Ja das WorkingDirectory ist ja das, wo die befehle dann relativ dazu ausgeführt werden, machen vielleicht meine kommentare hier (https://github.com/juwi/palava-ansible/pull/10#pullrequestreview-536053000) das klarer?

**Comment by farao** [comment]
Weitere Anmerkung: Ich weiß, dass wir hier erstmal nur auf ein schnelles aufsetzen eines signaltowers aus sind - aber um die skripte dann auch für uns nutzen zu können muss es möglich sein, 2 signaltower auf einem server aufzusetzen, wie es momentan bei uns mit staging (für https://staging.palava.tv) und production (https://palava.tv) der Fall ist. Eventuell sollten wir also den installationsort ($WorkingDirectory), den namen des systemd unit files und den release command (MIX_ENV=dev mix release staging vs. MIX_ENV=prod mix release production) mit den production defaults belegen aber konfigurierbar machen damit wir für uns den staging tower zusätzlich aufsetzen können?

Und wenn wir die skripte dann so haben, können wir das wie bisher eigentlich auch irgendwie über einen git hook starten, damit ein git push auf den server (nicht auf github) ein deploy ist oder funktinoiert das dann anders?
